// Data-driven definition of every unisole-engine resource.
// Each entry drives the sidebar, the table columns, the create/edit form,
// and the custom (GET) actions. Field types:
//   text, textarea, number, boolean, datetime, select, json
export const resources = [
  {
    name: "users",
    label: "Users",
    path: "/api/users",
    required: ["name", "email"],
    passwordAction: { url: (id) => `/api/users/${id}/password` },
    fields: [
      { key: "id", label: "User ID", type: "text" },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "email", label: "Email", type: "text", required: true },
      { key: "phone", label: "Phone", type: "text" },
      { key: "password", label: "Password", type: "password", hideInTable: true },
      { key: "role", label: "Role", type: "select", options: ["student", "admin"] },
      {
        key: "auth_provider",
        label: "Auth Provider",
        type: "select",
        options: ["local", "google", "supabase"],
      },
      { key: "is_verified", label: "Verified", type: "boolean" },
      { key: "created_at", label: "Created At", type: "datetime" },
      { key: "updated_at", label: "Updated At", type: "datetime" },
    ],
  },
  {
    name: "categories",
    label: "Categories",
    path: "/api/categories",
    required: ["name"],
    fields: [
      { key: "id", label: "Category ID", type: "text" },
      { key: "name", label: "Name", type: "text", required: true },
    ],
  },
  {
    name: "courses",
    label: "Courses",
    path: "/api/courses",
    required: ["title", "slug"],
    fields: [
      { key: "id", label: "Course ID", type: "text" },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "category_id", label: "Category ID", type: "text" },
      { key: "price", label: "Price", type: "number" },
      { key: "rating_avg", label: "Avg Rating", type: "number" },
      { key: "total_enrollments", label: "Enrollments", type: "number" },
      { key: "created_at", label: "Created At", type: "datetime" },
      { key: "updated_at", label: "Updated At", type: "datetime" },
    ],
    actions: [
      { label: "Modules", url: (id) => `/api/courses/${id}/modules` },
      { label: "Tree", url: (id) => `/api/courses/${id}/tree` },
    ],
  },
  {
    name: "modules",
    label: "Modules",
    path: "/api/modules",
    required: ["title"],
    fields: [
      { key: "id", label: "Module ID", type: "text" },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "course_id", label: "Course ID", type: "text" },
      { key: "order_index", label: "Order Index", type: "number" },
    ],
  },
  {
    name: "module-items",
    label: "Module Items",
    path: "/api/module-items",
    required: ["title", "type"],
    fields: [
      { key: "id", label: "Module Item ID", type: "text" },
      { key: "module_id", label: "Module ID", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: ["video", "pdf", "article", "quiz", "assignment"],
        required: true,
      },
      { key: "content_url", label: "Content URL", type: "text" },
      { key: "content_body", label: "Content Body", type: "textarea", hideInTable: true },
      { key: "order_index", label: "Order Index", type: "number" },
    ],
  },
  {
    name: "assignments",
    label: "Assignments",
    path: "/api/assignments",
    required: ["title"],
    fields: [
      { key: "id", label: "Assignment ID", type: "text" },
      { key: "lesson_id", label: "Lesson ID", type: "text" },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "max_score", label: "Max Score", type: "number" },
      { key: "due_date", label: "Due Date", type: "datetime" },
      { key: "allowed_attempts", label: "Allowed Attempts", type: "number" },
    ],
  },
  {
    name: "assignment-submissions",
    label: "Assignment Submissions",
    path: "/api/assignment-submissions",
    required: ["assignment_id", "user_id"],
    fields: [
      { key: "id", label: "Submission ID", type: "text" },
      { key: "assignment_id", label: "Assignment ID", type: "text", required: true },
      { key: "user_id", label: "User ID", type: "text", required: true },
      { key: "file_url", label: "File URL", type: "text" },
      { key: "submitted_at", label: "Submitted At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: ["pending", "graded"] },
      { key: "score", label: "Score", type: "number" },
    ],
  },
  {
    name: "tests",
    label: "Tests",
    path: "/api/tests",
    required: ["title"],
    fields: [
      { key: "id", label: "Test ID", type: "text" },
      { key: "module_item_id", label: "Module Item ID", type: "text" },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "duration_min", label: "Duration (min)", type: "number" },
      { key: "total_marks", label: "Total Marks", type: "number" },
      { key: "passing_marks", label: "Passing Marks", type: "number" },
      { key: "max_attempts", label: "Max Attempts", type: "number" },
    ],
  },
  {
    name: "test-attempts",
    label: "Test Attempts",
    path: "/api/test-attempts",
    required: ["test_id", "user_id"],
    fields: [
      { key: "id", label: "Test Attempt ID", type: "text" },
      { key: "test_id", label: "Test ID", type: "text", required: true },
      { key: "user_id", label: "User ID", type: "text", required: true },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["in_progress", "submitted", "evaluated"],
      },
      { key: "score", label: "Score", type: "number" },
      { key: "answers", label: "Answers (JSON)", type: "json" },
    ],
  },
  {
    name: "carts",
    label: "Carts",
    path: "/api/carts",
    required: ["user_id"],
    fields: [
      { key: "id", label: "Cart ID", type: "text" },
      { key: "user_id", label: "User ID", type: "text", required: true },
    ],
  },
  {
    name: "coupons",
    label: "Coupons",
    path: "/api/coupons",
    required: ["code", "discount_type"],
    fields: [
      { key: "id", label: "Coupon ID", type: "text" },
      { key: "code", label: "Code", type: "text", required: true },
      { key: "discount_type", label: "Discount Type", type: "select", options: ["flat", "percent"], required: true },
      { key: "value", label: "Value", type: "number" },
      { key: "max_uses", label: "Max Uses", type: "number" },
      { key: "used_count", label: "Used Count", type: "number" },
      { key: "valid_from", label: "Valid From", type: "datetime" },
      { key: "valid_to", label: "Valid To", type: "datetime" },
    ],
  },
  {
    name: "enrollments",
    label: "Enrollments",
    path: "/api/enrollments",
    required: ["user_id", "course_id"],
    fields: [
      { key: "id", label: "Enrollment ID", type: "text" },
      { key: "user_id", label: "User ID", type: "text", required: true },
      { key: "course_id", label: "Course ID", type: "text", required: true },
      { key: "enrolled_at", label: "Enrolled At", type: "datetime" },
      { key: "expiry_at", label: "Expires At", type: "datetime" },
      { key: "progress_percent", label: "Progress %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "completed", "expired"] },
    ],
  },
  {
    name: "orders",
    label: "Orders",
    path: "/api/orders",
    required: ["user_id"],
    fields: [
      { key: "id", label: "Order ID", type: "text" },
      { key: "user_id", label: "User ID", type: "text", required: true },
      { key: "razorpay_order_id", label: "Razorpay Order ID", type: "text" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["created", "paid", "failed", "refunded"] },
      { key: "coupon_id", label: "Coupon ID", type: "text" },
    ],
  },
  {
    name: "order-items",
    label: "Order Items",
    path: "/api/order-items",
    required: ["order_id", "course_id"],
    fields: [
      { key: "id", label: "Order Item ID", type: "text" },
      { key: "order_id", label: "Order ID", type: "text", required: true },
      { key: "course_id", label: "Course ID", type: "text", required: true },
      { key: "price_at_purchase", label: "Price at Purchase", type: "number" },
    ],
  },
  {
    name: "payments",
    label: "Payments",
    path: "/api/payments",
    required: ["order_id"],
    fields: [
      { key: "id", label: "Payment ID", type: "text" },
      { key: "order_id", label: "Order ID", type: "text", required: true },
      { key: "razorpay_payment_id", label: "Razorpay Payment ID", type: "text" },
      { key: "razorpay_signature", label: "Razorpay Signature", type: "text" },
      { key: "method", label: "Method", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["captured", "failed", "refunded"] },
    ],
  },
  {
    name: "certificates",
    label: "Certificates",
    path: "/api/certificates",
    required: ["user_id", "course_id"],
    fields: [
      { key: "id", label: "Certificate ID", type: "text" },
      { key: "user_id", label: "User ID", type: "text", required: true },
      { key: "course_id", label: "Course ID", type: "text", required: true },
      { key: "certificate_url", label: "Certificate URL", type: "text" },
    ],
  },
  {
    name: "reviews",
    label: "Reviews",
    path: "/api/reviews",
    required: ["user_id", "course_id", "rating"],
    fields: [
      { key: "id", label: "Review ID", type: "text" },
      { key: "user_id", label: "User ID", type: "text", required: true },
      { key: "course_id", label: "Course ID", type: "text", required: true },
      { key: "rating", label: "Rating (1-5)", type: "number", required: true },
      { key: "comment", label: "Comment", type: "textarea" },
    ],
  },
];
